apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    chart: argo-rollouts
    helm:
      values: |
        dashboard:
          enabled: false
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 2.31.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true