# https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/#helm-value-files-from-external-git-repository

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: default
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd    
      targetRevision: 5.41.2
      helm:
        valueFiles:
        - $values/argocd-learning/charts/argocd/values.yaml
    - repoURL: https://github.com/Vinaum8/k8s-learning.git
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true