apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: default
  source:
    chart: kube-prometheus-stack
    helm:
      values: |
        prometheus.prometheusSpec.podMonitorSelectorNilUsesHelmValues: false
        prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues: false
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 48.2.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true