apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-applications
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: core
  source:
    path: argocd-learning/apps/
    repoURL: https://github.com/Vinaum8/k8s-learning.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true